name: saju_app
description: "사주 기반 소개팅 앱 - 운명적 만남을 찾아주는 사주인연"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- 상태관리 ---
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # --- 라우팅 ---
  go_router: ^14.8.1

  # --- Backend (Supabase) ---
  supabase_flutter: ^2.9.0

  # --- 코드 생성 모델 ---
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # --- 결제 ---
  purchases_flutter: ^8.4.1  # RevenueCat

  # --- 소셜 로그인 ---
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.2.2
  # kakao_flutter_sdk_user: ^1.9.6  # TODO: Kakao 개발자 등록 후 활성화

  # --- UI ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  # --- 관상 (Face Reading) ---
  google_mlkit_face_detection: ^0.13.2
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- 코드 생성 ---
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  # custom_lint: any       # TODO: analyzer 호환 버전 나오면 복원
  # riverpod_lint: any     # TODO: analyzer 호환 버전 나오면 복원

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters/namuri/
    - assets/images/characters/namuri/expressions/
    - assets/images/characters/namuri/poses/
    - assets/images/characters/namuri/views/
    - assets/images/characters/namuri_girlfriend/
    - assets/images/characters/namuri_girlfriend/expressions/
    - assets/images/characters/namuri_girlfriend/poses/
    - assets/images/characters/namuri_girlfriend/views/
    - assets/images/characters/bulkkori/
    - assets/images/characters/bulkkori/poses/
    - assets/images/characters/bulkkori/views/
    - assets/images/characters/heuksuni/
    - assets/images/characters/heuksuni/expressions/
    - assets/images/characters/heuksuni/poses/
    - assets/images/characters/heuksuni/views/
    - assets/images/characters/soedongi/
    - assets/images/characters/soedongi/expressions/
    - assets/images/characters/soedongi/poses/
    - assets/images/characters/soedongi/views/
    - assets/images/characters/mulgyeori/
    - assets/images/characters/mulgyeori/expressions/
    - assets/images/characters/mulgyeori/poses/
    - assets/images/characters/mulgyeori/views/
    - assets/images/characters/gold_tokki/
    - assets/images/characters/gold_tokki/expressions/
    - assets/images/characters/gold_tokki/poses/
    - assets/images/characters/gold_tokki/views/
    - assets/images/characters/black_tokki/
    - assets/images/characters/black_tokki/expressions/
    - assets/images/characters/black_tokki/poses/
    - assets/images/characters/black_tokki/views/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
